//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparation
    {
        public int PreparationID { get; set; }
        public string PName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Description_ { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Type_ Type_ { get; set; }
    }
}
